## [그림 1.8] Team ID 값 입력
#APPLE.TEAM.ID=[Team ID]
## [그림 2.5] Return URLs 값 입력
#APPLE.WEBSITE.URL=[Website URLs]
## [그림 2.6] Identifier 값 입력
#APPLE.AUD=[Client ID]
## [그림 3.5] Key ID 값 입력
#APPLE.KEY.ID=[Key ID]d
## [그림 3.5]에서 다운로드 받은 Private Key 파일을 해당 위치로 이동 후, 파일명 입력
#APPLE.KEY.PATH=static/AuthKey_[KeyID].p8
# application.yml
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET:}      # Kakao PKCE만 쓰면 비워도 OK
            scope: profile, account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST          # Kakao 권장
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          # Google 은 기본값이 내장돼 있으므로 provider 블록 생략 가능
